services:
  app:
    container_name: nestjs_calendar_app_app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app:delegated
      - /app/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "npm run build && npm run start:prod"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - nestjs_calendar_app_net

  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nestjs_calendar_app_net

volumes:
  postgres_data:
    name: nestjs_calendar_app_postgres_data

networks:
  nestjs_calendar_app_net:
    name: nestjs_calendar_app_network
    driver: bridge